
CREATE TABLE PAPA (ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2 (40), EDAD INTEGER);
CREATE TABLE HIJOMAYOR(ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2 (40), EDAD INTEGER);
CREATE TABLE HIJOMENOR(ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2 (40), EDAD INTEGER);

SELECT * FROM HIJOMENOR;

CREATE OR REPLACE TRIGGER DISP_PAPA AFTER INSERT ON PAPA FOR EACH ROW 
BEGIN 
IF :NEW.EDAD > 18 THEN
INSERT INTO HIJOMAYOR VALUES(:NEW.ID, :NEW.NOMBRE, :NEW.EDAD);
ELSE
INSERT INTO HIJOMENOR VALUES(:NEW.ID, :NEW.NOMBRE, :NEW.EDAD);
END IF;
END;
/

---- VAMOS A INSERTAR PAPA ----

INSERT INTO PAPA VALUES(1,'IVAN',23);
INSERT INTO PAPA VALUES(2,'ANA',15);

SELECT * FROM PAPA;
SELECT * FROM HIJOMAYOR;
SELECT * FROM HIJOMENOR;

---- EJERCICIO 3 ----

CREATE TABLE TRABAJADOR(ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2(40), SUELDO_BASE FLOAT);
CREATE TABLE RESPALDO(ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2(40), SUELDO_BASE FLOAT);

create or replace procedure guardar_trabajador(my_id OUT integer,
                  my_nombre IN varchar2, my_sueldo_base IN float)
AS
BEGIN
insert into trabajador values(my_id,my_nombre,my_edad);
END;
/

create or replace procedure eliminar_trabajador(my_id OUT integer,
                  my_nombre IN varchar2, my_sueldo_base IN float)
AS
BEGIN
delete from trabajador values(my_id,my_nombre,my_edad);
END;
/





