---- EJERCICIO 3 ----

CREATE TABLE TRABAJADOR(ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2(40), SUELDO_BASE FLOAT);
CREATE TABLE RESPALDO(ID INTEGER , NOMBRE VARCHAR2(40), SUELDO_BASE FLOAT);

CREATE OR REPLACE PROCEDURE CONTAR(NUMERO OUT INTEGER)
AS
BEGIN
SELECT COUNT(*) INTO NUMERO FROM TRABAJADOR;

DBMS_OUTPUT.PUT_LINE('BUSCADOS  '||NUMERO);
END;
/

--COPIAR
CREATE OR REPLACE PROCEDURE COPIA 
AS
CURSOR CUR_TRABAJADOR IS SELECT * FROM TRABAJADOR;
BEGIN
FOR REC IN CUR_TRABAJADOR LOOP
INSERT INTO RESPALDO VALUES(REC.ID, REC.NOMBRE, REC.SUELDO_BASE);
END LOOP;
END;
/

CREATE OR REPLACE TRIGGER DISP_TRABAJADOR BEFORE INSERT ON TRABAJADOR FOR EACH ROW 
DECLARE
VALOR INTEGER;
BEGIN
CONTAR(VALOR);
IF VALOR=3 THEN
COPIA();
DELETE FROM TRABAJADOR;
END IF;
END;
/

SELECT * FROM TRABAJADOR;
SELECT * FROM RESPALDO;
INSERT INTO TRABAJADOR VALUES(1,'IVAN', 15000);
INSERT INTO TRABAJADOR VALUES(2,'JAVIER',15500);
INSERT INTO TRABAJADOR VALUES(3,'VALERIA',12500);
INSERT INTO TRABAJADOR VALUES(4,'MIGUEL',15620);
